export const ROUTES = {
  HOME: '/',
  ABOUT_US: '/about-us',
  APPLY_FOR_JOBS: '/apply-for-jobs',
  APPLY_SCHEDULE_MEETING: '/apply-schedule-meeting',
  PARTNERSHIP_PROGRAMME: '/partnership-programme',
  AWARDS: '/awards',
  DEO: '/deo',

  ACADEMICIANS: '/academicians',
  RESEARCH_PAPER_PUBLICATION_SERVICES: '/research-paper-publication-services',
  EDITORIAL_BOARD_MEMBERSHIP: '/editorial-board-membership',
  MEMBERSHIP_OTHERS: '/membership-others',
  SERVICES_TO_MEMBERS: '/services-to-members',
  BOOKS_PUBLICATION_SERVICES: '/books-publication-services',
  APPLY_FOR_FELLOWSHIP: '/apply-for-fellowship',
  APPLY_FOR_PATENT_REGISTRATION: '/apply-for-patent-registration',
  MOOC_SUPPORTS: '/mooc-supports',
  ACADEMIC_INSTITUTIONAL_PARTNERS: '/academic-institutional-partners',

  RND_EBI: '/rnd-ebi',
  EDWIN_ACADEMIC_IMMIGRATION_SOLUTIONS: '/edwin-academic-immigration-solutions',
  ONLINE_MEMBERSHIP_ARTICLES_ACCESSING: '/online-membership-articles-accessing',
  APPLY_NOW_WRITING_ASSISTANCE: '/apply-now-writing-assistance',
  FACULTY_CO_GUIDE_REGISTRATION: '/faculty-co-guide-registration',
  INCREASE_CITATION_DOI: '/increase-citation-doi',
  APPLY_FOR_PATENT_SUPPORT: '/apply-for-patent-support',
  APPLY_FOR_GRANTS: '/apply-for-grants',
  APPLY_FOR_PLAGIARISM_DETECTOR: '/apply-for-plagiarism-detector',
  APPLY_FOR_TURNITIN_SUPPORT: '/apply-for-turnitin-support',
  APPLY_FOR_API_CALCULATOR: '/apply-for-api-calculator',

  EDUCATIONAL: '/educational',
  ACADEMIC_NEWS_CHANNEL: '/academic-news-channel',
  APPLY_FOR_NEWS: '/apply-for-news',
  NGO_SUPPORT: '/ngo-support',
  INTERNATIONAL_EDUCATIONAL_TOURS: '/international-educational-tours',
  PHD_PROGRAMMES: '/phd-programmes',
  PG_PROGRAMMES: '/pg-programmes',
  UG_PROGRAMMES: '/ug-programmes',
  ONLINE_LEARNING_MOOC: '/online-learning-mooc',
  HELP_FOR_EDUCATION: '/help-for-education',

  UNIVERSITY_COLLEGE: '/university-college',
  APPLY_FOR_NAAC_SUPPORT: '/apply-for-naac-support',
  APPLY_FOR_HR_SUPPORT: '/apply-for-hr-support',
  APPLY_FOR_NBA_TRAINING_SUPPORT: '/apply-for-nba-training-support',
  SUPPORT_FOR_PROCEEDING_PRINTING: '/support-for-proceeding-printing',
  PAPER_PUBLICATION_SUPPORT: '/paper-publication-support',
  SPONSORSHIP_FOR_ORGANIZING_CONFERENCE: '/sponsorship-for-organizing-conference',
  NEED_RESOURCE_PERSON: '/need-resource-person',
  ADVERTISEMENT_SUPPORT: '/advertisement-support',
  MEMBERSHIP_DELLNETT: '/membership-dellnett',
  NAAC_ASSISTANCE: '/naac-assistance',

  EDITORS_NGO_BUSINESS: '/editors-ngo-business',
  OPENING_JOURNAL_SERVICES: '/opening-journal-services',
  TECHNICAL_SUPPORT_FOR_INDEXING: '/technical-support-for-indexing',
  PRINT_EISSN_ALLOTMENT_SUPPORT: '/print-eissn-allotment-support',
  FREE_DOI: '/free-doi',
  PAID_DOI_CROSSREF: '/paid-doi-crossref',
  DOI_PORTAL: '/doi-portal',
  MEMBERSHIP_PORTAL: '/membership-portal',
  CSR_FUNDING_ASSISTANT: '/csr-funding-assistant',
  BUSINESS_AUTOMATION: '/business-automation',
  DIGAL_MARKETING: '/digital-marketing',
  APPS_FOR_IOS_AND_ANDROID: '/apps-for-ios-and-android',
  WHATSAPP_SERVICES: '/whatsapp-services',
  HR_SUPPORT_FOR_BUSINESS: '/hr-support-for-business',

  PAY_NOW: '/pay-now',
  PAYNOW: '/paynow',
  FAQ: '/faq',
  FEEDBACK_COMPLAINT_BOX: '/feedback-complaint-box',

  GALLERY: '/gallery',
  CONFERENCES: '/conferences',
  BIRTHDAYS: '/birthdays',
  NATIONAL_CELEBRATIONS: '/national-celebrations',

  PRESS: '/press',
  CONTACT: '/contact',
};
